### ISSUE TITLE
Cookie length too long results in Bad Request

### ISSUE THREAD

**Issue by ericfranz** [OSC/Open-OnDemand#26]
```
Bad Request

Your browser sent a request that this server could not understand.
Size of a request header field exceeds server limit.

Apache/2.4.25 (Red Hat) Server at apps-test.awesim.org Port 443
```

The reason is that 

I thought that this had attempted to fix the problem: https://github.com/OSC/ood_appkit/pull/42. But that only affects Rails and perhaps some of our apps haven't been updated recently either.

My total cookie length was 8756 bytes. Including

* `_dashboard_session`, `_job_status_session`, `_weld_predictor_session`, `_my_app_session`, `_ood_app_session`, each around 350 bytes long (1750 bytes)
* shibsession_ cookie around 300 bytes long.
* 9 mod_auth_openidc_state_ cookies around 700 bytes long each (around 6300 bytes)

According to https://github.com/pingidentity/mod_auth_openidc/wiki/Cookies, the mod_auth_openidc_state_ cookie is supposed to be deleted "when the user returns to the Apache server with an authentication response (indicating either success or failure). It is (should be) short-lived and its lifetime can be configured with the OIDCStateTimeout configuration primitive for which the default is 5 minutes. Note that the lifetime is enforced at the server by mod_auth_openidc, not by the lifetime of the cookie."

Perhaps since this is a test server, the OIDCStateTimeout was modified to be something very large.

But even then, it seems like we have a few apps that need to have their session cookies set with paths appropriately. Also, this should probably be something we do in all example apps that could possibily set a cookie (i.e. Sinatra example apps).

**Comment by nickjer** [comment]
This will affect only OnDemand portals that use `mod_auth_openidc`.

The culprit is most likely an app that does AJAX polling and doesn't use the proper header when making the requests. All AJAX requests should have the header:

```http
X-Requested-With: XMLHttpRequest
```

The issue is that when a user is logged out the module `mod_auth_openidc` will create a state cookie and attempt to redirect the user to login. This works fine if the request was initiated by the user. But if the request is initiated by an AJAX request in the background that continues to poll, then you will quickly fill up with state cookies.

The solution `mod_auth_openidc` implemented is to scan for requests with the above header and return HTTP 401 instead of attempting to log the user back in.

By default jQuery adds this header to all AJAX requests. And I believe all Open OnDemand core apps properly set this header (with special care paid to the File Explorer and previously the Shell app as they don't use jQuery). If you do find the culprit app please open an issue under the app's repo so we can get it resolved as soon as possible.
